/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110232-g1e91a39502-20230413"
#endif /* AVUTIL_FFVERSION_H */
